[package]
name = "bletest"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
btleplug = "0.10.4"
rand = "0.8.5"
tokio = { version = "1.25.0", features = ["full"] }
uuid = "1.2.2"
